#   _                           _ _
#  | |                         (_) |
#  | |     __ _ _____   _  __ _ _| |_
#  | |    / _` |_  / | | |/ _` | | __|
#  | |___| (_| |/ /| |_| | (_| | | |_
#  \_____/\__,_/___|\__, |\__, |_|\__|
#                    __/ | __/ |
#                   |___/ |___/

gui:
  showRandomTip: false
  showBottomLine: false
  nerdFontsVersion: '3'
  border: 'single'
git:
  log:
    showGraph: 'always'
  parseEmoji: true
customCommands:
  - key: 'C'
    command: 'clear && git cz c'
    description: 'Commit with commitizen'
    context: 'files'
    loadingText: 'opening commitizen commit tool'
    subprocess: true
  - key: 'u'
    command: 'git undo'
    description: 'Undo last commit'
    context: 'files'
