#   _
#  | |
#  | | _____ _   _ _ __ ___   __ _ _ __
#  | |/ / _ \ | | | '_ ` _ \ / _` | '_ \
#  |   <  __/ |_| | | | | | | (_| | |_) |
#  |_|\_\___|\__, |_| |_| |_|\__,_| .__/
#             __/ |               | |
#            |___/                |_|

[manager]
