# ---------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# ---------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#16161e'
foreground = '#c0caf5'

[colors.cursor]
cursor = '#c0caf5'
text   = '#16161e'

# Normal colors
[colors.normal]
black   = '#15161e'
blue    = '#7aa2f7'
cyan    = '#7dcfff'
green   = '#9ece6a'
magenta = '#bb9af7'
red     = '#f7768e'
white   = '#a9b1d6'
yellow  = '#e0af68'

# Bright colors
[colors.bright]
black   = '#414868'
blue    = '#7aa2f7'
cyan    = '#7dcfff'
green   = '#9ece6a'
magenta = '#bb9af7'
red     = '#f7768e'
white   = '#c0caf5'
yellow  = '#e0af68'

# Indexed Colors
[[colors.indexed_colors]]
color = '#ff9e64'
index = 16

[[colors.indexed_colors]]
color = '#db4b4b'
index = 17
