
name = 'Michael Olson'
email = 'michaelolson84@gmail.com'

[nodejs]
version = '20.4.0'
installer = 'npm install -g'
globals = ['aws-cdk', '@nestjs/cli', 'turbo', 'typeorm', 'yarn']

[python]
version = '3.11.3'
installer = 'pip install -U'
globals = ['black', 'ruff', 'ruff-lsp']
