
name = 'Michael Olson'
email = 'michaelolson84@gmail.com'

[nodejs]
version = '20.9.0'
installer = 'npm install -g'
globals = ['@nestjs/cli', 'neovim', 'turbo', 'yarn']

[python]
version = '3.11.6'
installer = 'pip install -U'
globals = ['black', 'ruff', 'ruff-lsp']
