---@class PlenaryLogger
---@field error fun(msg: any, opts: any)
---@field warn fun(msg: any, opts: any)
---@field info fun(msg: any, opts: any)
---@field log fun(msg: any, opts: any)
---@field debug fun(msg: any, opts: any)
