[packages.arch]
apps = [
  'chromium',
  'ghostty',
  'obs-studio',
  'obsidian',
  'seahorse',
  'slack-desktop',
  'spotify',
  'thunderbird',
  'vlc',
  'zed',
  'zen-browser-bin',
  'zoom',
]
tools = [
  'amazon-ecr-credential-helper',
  'aws-cli-bin',
  'aws-sam-cli-bin',
  'aws-session-manager-plugin',
  'azure-cli',
  'docker',
  'docker-compose',
  'fastfetch',
  'github-cli',
  'kubectl',
  'man-db',
  'man-pages',
  'minikube',
  'ookla-speedtest-bin',
  'terraform',
  'ttf-jetbrains-mono',
  'ttf-jetbrains-mono-nerd',
  'ttf-nerd-fonts-symbols-mono',
  'v4l2loopback-utils',
  'vivify-bin',
  'wl-clip-persist',
  'wl-clipboard',
]

[[packages.arch.pwa]]
name = 'Discord'
url  = 'https://discord.com/app'
icon = 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/discord.png'

[[packages.arch.pwa]]
name = 'Pocket Casts'
url  = 'https://pocketcasts.com/podcasts'
icon = 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/pocket-casts.png'

[[packages.arch.pwa]]
name = 'Twitch'
url  = 'https://twitch.tv'
icon = 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/twitch.png'

[[packages.arch.pwa]]
name = 'YouTube'
url  = 'https://youtube.com'
icon = 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/youtube.png'
