#                        _
#                       (_)
#   _ __ ___   __ _ _ __ _ _ __ ___   ___
#  | '_ ` _ \ / _` | '__| | '_ ` _ \ / _ \
#  | | | | | | (_| | |  | | | | | | | (_) |
#  |_| |_| |_|\__,_|_|  |_|_| |_| |_|\___/
#
#


[package_management]
manager = "uv"

[formatting]
line_length = 120

[completion]
activate_on_typing = true
copilot            = true

[save]
format_on_save = true

[server]
browser        = "default"
follow_symlink = false

[runtime]
auto_instantiate = false
auto_reload      = "off"
on_cell_change   = "autorun"
watcher_on_save  = "lazy"
reactive_tests   = true

[display]
cell_output           = "below"
code_editor_font_size = 12
dataframes            = "rich"
default_width         = "medium"
theme                 = "dark"

[language_servers.pylsp]
enabled     = true
enable_ruff = true
enable_mypy = true

[diagnostics]
enabled = true

[keymap]
preset = "vim"

[keymap.overrides]

[snippets]
include_default_snippets = true
custom_paths             = []

[experimental]
