# ---------------------------------------------------------------------------
# Configure the appearance of Alacritty.
# ---------------------------------------------------------------------------

import = ['~/.config/alacritty/themes/tokyonight.toml']

[window]
dimensions    = { columns = 120, lines = 40 }
dynamic_title = false
padding       = { x = 4, y = 4 }
title         = 'Terminal'

[colors]
draw_bold_text_with_bright_colors = true
