# ---------------------------------------------------------------------------
# Configure the keybinds used in Alacritty.
# ---------------------------------------------------------------------------

[keyboard]
[[keyboard.bindings]]
key    = "Paste"
action = "Paste"

[[keyboard.bindings]]
key    = "Copy"
action = "Copy"

[[keyboard.bindings]]
key    = "L"
mods   = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key   = "L"
mods  = "Control"
mode  = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key    = "PageUp"
mods   = "Shift"
mode   = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key    = "PageDown"
mods   = "Shift"
mode   = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key    = "Home"
mods   = "Shift"
mode   = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key    = "End"
mods   = "Shift"
mode   = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key    = "V"
mods   = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key    = "C"
mods   = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key    = "F"
mods   = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key    = "B"
mods   = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key    = "C"
mods   = "Control|Shift"
mode   = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key    = "Key0"
mods   = "Control"
action = "ResetFontSize"
