# ---------------------------------------------------------------------------
# Configure the keybinds used in Alacritty.
# ---------------------------------------------------------------------------

[keyboard]
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]
