#       _ _
#      | (_)
#    __| |_ _ __ ___ _ ____   __
#   / _` | | '__/ _ \ '_ \ \ / /
#  | (_| | | | |  __/ | | \ V /
#   \__,_|_|_|  \___|_| |_|\_/
#
#

[global]
load_dotenv = false

[whitelist]
prefix = ["~/source"]
