#       _                 _     _
#      | |               | |   (_)
#   ___| |_ __ _ _ __ ___| |__  _ _ __
#  / __| __/ _` | '__/ __| '_ \| | '_ \
#  \__ \ || (_| | |  \__ \ | | | | |_) |
#  |___/\__\__,_|_|  |___/_| |_|_| .__/
#                                | |
#                                |_|


# ========================================
# General
# ========================================

add_newline = false
continuation_prompt = "▶▶ "
format = """
$os\
$shell\
$username\
$directory\
${custom.git_icon}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character
"""
right_format = "$all"

[cmd_duration]
disabled = true
format   = "[took $duration]($style)"
style    = "101"

[directory]
read_only        = " 󰌾"
truncate_to_repo = true

[package]
disabled = true
symbol   = "󰏗 "


# ========================================
# System
# ========================================

[battery]
charging_symbol    = "⚡️ "
disabled           = true
discharging_symbol = "💀 "
full_symbol        = "🔋 "

[hostname]
disabled   = false
ssh_only   = true
ssh_symbol = " "

[memory_usage]
disabled = true
symbol   = "󰍛 "

[os]
disabled = false
format   = "[$symbol]($style)"

[os.symbols]
Alpaquita        = " "
Alpine           = " "
Amazon           = " "
Android          = " "
Arch             = " "
Artix            = " "
CentOS           = " "
Debian           = " "
DragonFly        = " "
Emscripten       = " "
EndeavourOS      = " "
Fedora           = " "
FreeBSD          = " "
Garuda           = "󰛓 "
Gentoo           = " "
HardenedBSD      = "󰞌 "
Illumos          = "󰈸 "
Linux            = " "
Mabox            = " "
Macos            = " "
Manjaro          = " "
Mariner          = " "
MidnightBSD      = " "
Mint             = " "
NetBSD           = " "
NixOS            = " "
OpenBSD          = "󰈺 "
OracleLinux      = "󰌷 "
Pop              = " "
Raspbian         = " "
RedHatEnterprise = " "
Redhat           = " "
Redox            = "󰀘 "
SUSE             = " "
Solus            = "󰠳 "
Ubuntu           = " "
Unknown          = " "
Windows          = "󰍲 "
openSUSE         = " "


# ========================================
# Languages
# ========================================

[c]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[dart]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[dotnet]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[golang]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[lua]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[nodejs]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = "󰎙 "

[python]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[ruby]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[rust]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "

[zig]
format         = "[$symbol$version]($style) "
version_format = "${raw}"
symbol         = " "


# ========================================
# Services
# ========================================

[aws]
disabled          = false
expiration_symbol = " "
format            = "[$symbol$profile]($style) "
profile_aliases   = { mhs-dev = "dev" }
region_aliases    = { us-east-1 = "VA", us-east-2 = "OH" }
symbol            = " "

[gcloud]
disabled = false
symbol   = "󱇶 "

[terraform]
disabled = false
format   = "[$symbol$workspace]($style) "
symbol   = " "


# ========================================
# Source control
# ========================================

[custom.git_icon]
command = """
  symbol="󰊢 "
  remote=$(command git ls-remote --get-url 2> /dev/null)
  if [[ "$remote" =~ "azure" ]]; then symbol=" "; fi
  if [[ "$remote" =~ "bitbucket" ]]; then symbol="󰂨 "; fi
  if [[ "$remote" =~ "github" ]]; then symbol=" "; fi
  if [[ "$remote" =~ "gitlab" ]]; then symbol=" "; fi
  echo "$symbol"
"""
description = "Display symbol for git repository."
disabled = true
format = "[$output]($style)  "
shell = ["--noprofile", "--norc", "bash"]
style = "bold white"
when = "git rev-parse --is-inside-work-tree 2> /dev/null"

[fossil_branch]
symbol = " "

[git_branch]
disabled = false
format   = "[$symbol$branch]($style) "
symbol   = " "

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[hg_branch]
symbol = " "

[pijul_channel]
symbol = "🪺 "


# ========================================
# Additional modules
# ========================================

[docker_context]
symbol = " "

[helm]
symbol = "󰠳 "

[kubernetes]
symbol = "󱃾 "
