name: macOS

on: [workflow_dispatch]

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
